#CI项目
name: ipq60xx-lede

#CI计划
on:
  # 手动执行
  workflow_dispatch:
  # 默认为utc时间，北京时间需要减去8

#CI权限
permissions: write-all

#CI任务
jobs:
  build:
    name: ipq60xx-lede

    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/core.yml
    with:
      #编译平台
      TARGET: ipq60xx-lede
      #源码
      REPO_SOURCE: lede
      #源码地址
      REPO_URL: https://github.com/coolsnowwolf/lede.git
      #源码分支
      REPO_BRANCH: master
      #软件源
      FEEDS_CONF: feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/jdcloud-re-ss-01.config
